main/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("library.urls")),
    path("", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
]

main/library/models.py
import re
from django.db import models
from taggit.managers import TaggableManager

class BookType(models.Model):
    booktype = models.CharField(max_length=30)

    @property
    def url(self):
        return f'{self.booktype}'.lower()

    def __str__(self):
        return f'{self.booktype}'

class Genre(models.Model):
    booktype = models.ForeignKey(BookType, on_delete=models.CASCADE)
    genre = models.CharField(max_length=50)

    @property
    def url(self):
        genre_str = f'{self.genre}'
        return '_'.join(re.findall(r'\w+', genre_str)).lower()

    class Meta:
        ordering = ['genre']

    def __str__(self):
        return f'{self.genre}:{self.booktype}'

class BookSeries(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f'{self.name}'

class Book(models.Model):
    STATUS_CHOICES = {
        "Y" : "Available",
        "O" : "On Loan",
        "R" : "Reserved",
        "U" : "Unavailable",
    }
    PERSON_CHOICES = {
        "R" : "Rayen",
        "D" : "Don",
        "C" : "Charlie",
        "S" : "Sam",
        "H" : "Honey",
        "A" : "Ash",
        "O" : "Soph",
        "N" : "None",
    }
    title = models.CharField(max_length=200, blank=True)
    author = models.CharField(max_length=200, blank=True)
    booktype = models.ForeignKey(BookType, on_delete=models.CASCADE, related_name='books')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='books')
    owner = models.CharField(max_length=1, choices=PERSON_CHOICES, default="N")
    blurb = models.CharField(max_length=1000, blank=True, default='')
    tags = TaggableManager()
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="Available")
    borrower = models.CharField(max_length=1, choices=PERSON_CHOICES, default="N")
    series = models.ForeignKey(BookSeries, on_delete=models.CASCADE, blank=True, default=2)
    volume = models.IntegerField(blank=True, default=0)
    
    class Meta:
        ordering = ['title']

    def __str__(self):
        return f'{self.title}:{self.author}'

main/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
</head>
<body>

<div class="container_{% block container %}{% endblock %}">
    {% include "header.html" %}
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/header.js' %}"></script>
</body>
</html>

main/templates/book_item.html
<tr id="row_{{ book.id }}" class="collapsed-row">
    <td>{{ book.title }}</td>
    <td>{{ book.author }}</td>
    <td>{{ book.get_status_display }}</td>
    <td>{{ book.get_owner_display }}</td>
    <td>
        <button class="iconbtn iconbtn-small action" expanded="false" id="{{ book.id }}" onclick="toggle_book(this.id)"><i class="fa black fa-angle-up" id="icon_{{ book.id }}"></i></button>
    </td>
    <tr class="hidden-info expanded-row" id="blurb_{{ book.id }}">
        {% if book.blurb %}
            <td class="long-text" colspan="2">{{ book.blurb }}</td>
        {% else %}
            <td colspan="2">-</td>
        {% endif %}
        <td colspan="3"></td>
    </tr>
    <tr class="hidden-info expanded-row" id="tags_{{ book.id }}">
        <td class="tags" colspan="5">
            Tags: {% for tag in book.tags.all %}{{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}
        </td>
    </tr>
    {% include "list_actions.html" %}
</tr>

main/templates/header.html
<header class="header">
    <div class="iconbtn-container">
        <button onclick="window.location.href='/';" class="iconbtn iconbtn-large"><i class="fa white fa-home"></i></button>
    </div>
    <div class="iconbtn-container">
        <button onclick="dropdown()" class="iconbtn iconbtn-large"><i class="fa white fa-bars"></i></button>
        <div id="menu" class="dropdown-content">
            <ul>
                {% for booktype in booktypelist %}
                <li><a href="/{{ booktype.url }}">{{ booktype }}</a>
                    <ul>
                        {% for genre in booktype.genre_set.all %}
                        {% if genre.url != "other" %}
                        <li><a href="/{{ booktype.url }}/{{ genre.url }}">{{ genre.genre }}</a></li>
                        {% endif %}
                        {% endfor %}
                        <li><a href="/{{ booktype.url }}/other">Other</a></li>
                    </ul>
                </li>
                {% endfor %}
                <li><a href="all">All books</a></li>
            </ul>
        </div>
    </div>

    <div>
        <button class="text-button text-small light centered" onclick="window.location.href='/user/{{ user.first_name }}';">My books</button>
    </div>
</header>

main/templates/home.html
{% extends "base.html" %}

{% block title %}Swag Library{% endblock %}

{% block container %}home{% endblock %}

{% block content %}
    <div class="image"></div>
    <div class="main">
        <div class="text-container">
            <h1>Welcome to the Library {{ user }}!</h1>
            <p>Click below to add a book, or browse the library via the menu above.</p>
            <p>Website by Rayen, art by Honey.</p>
            <button class="text-button text-large add-book" style="bottom: 60px;" onclick="window.location.href='/book';">Add a book</button>
        </div>
    </div>
{% endblock %}

main/templates/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block container %}list{% endblock %}

{% load lib_tags %}
{% block content %}
    <div class="main">
        <div class="text-container">
            <h1>{{ title }}</h1>
            <p>{{ intro }}</p>
            <div class="list-container">
            <table class="list-table">
                <tr class="header-row">
                    <th>Title</th>
                    <th>Author</th>
                    <th>Status</th>
                    <th>Owner</th>
                    <th></th>
                </tr>
                {% if list %}
                    {% for item in list %}
                        {% if item|get_value:'isSeries' == False %}
                            {% for book in item|get_value:'seriesBooks' %} {% include "book_item.html" %} {% endfor %}
                        {% else %}
                            <tr id="row_{{ forloop.counter }}" class="collapsed-row sublist">
                                <td>{{ item|get_value:'name' }}</td>
                                <td>{{ item|get_value:'author' }}</td>
                                <td>-</td>
                                <td>{{ item|get_value:'owner' }}</td>
                                <td>
                                    <button class="iconbtn iconbtn-small action" expanded="false" id="{{ forloop.counter }}" onclick="toggle_series(this.id)"><i class="fa black fa-angle-up" id="icon_{{ forloop.counter }}"></i></button>
                                </td>
                            </tr>
                            <tr class="hidden-info sublist" id="books_{{ forloop.counter }}">
                                <td colspan="5">
                                <table class="list-table">
                                    {% for book in item|get_value:'seriesBooks' %} {% include "book_item.html" %} {% endfor %}
                                </table>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% else %}
                   <tr>
                     <td class="list-no-items">No items have been added for this section yet :(</td>
                   </tr>
                {% endif %}
        </table>
        </div>
        <button class="text-button text-large add-book" onclick="window.location.href='/book';">Add a book</button>
        </div>
    </div>
    <script src="{% static 'js/list.js' %}"></script>
{% endblock %}

main/templates/list_actions.html
<tr class="hidden-info collapsed-row" id="actions_{{ book.id }}">

    <!-- Book owner actions: mark book as returned, make book unavailable, edit book -->
    {% if user.first_name == book.get_owner_display %}
        <td colspan="2"></td>
        {% if book.get_status_display == "On Loan" %}
            <td>
                <form method="POST" action="{% url 'borrow' %}">
                    {% csrf_token %}
                    <fieldset  class="hidden-info">
                        <input type="radio" name="book_id" value="{{ book.id }}" checked="checked">
                    </fieldset>
                    <button class="text-button text-small" type="submit" action="{% url 'borrow'%}">Returned</button>
                </form>
            </td>
        {% else %}
            <td></td>
        {% endif %}

        <td>
        {% if book.get_status_display == "Unavailable" %}
            <form method="POST" action="{% url 'availability' %}">
                {% csrf_token %}
                    <fieldset  class="hidden-info">
                        <input type="radio" name="book_id" value="{{ book.id }}" checked="checked">
                    </fieldset>
                <button class="text-button text-small" type="submit">Make available</button>
            </form>
        {% else %}
            <form method="POST" action="{% url 'availability' %}">
                {% csrf_token %}
                    <fieldset  class="hidden-info">
                        <input type="radio" name="book_id" value="{{ book.id }}" checked="checked">
                    </fieldset>
                <button class="text-button text-small" type="submit">Make unavailable</button>
            </form>
        {% endif %}
        </td>

        <td>
            <button class="iconbtn iconbtn-small action edit" onclick="window.location.href='/book/edit-id:{{ book.id }}';">
                <i class="fa white fa-pencil"></i>
            </button>
        </td>


    <!-- Book non-owner actions: borrow book if available, mark book as returned -->
    {% else %}
        <td colspan="3"></td>
        
            {% if book.get_status_display == "Available" %}
            <td></td>
            <td>
                <form method="POST" action="{% url 'borrow' %}">
                    {% csrf_token %}
                    <fieldset  class="hidden-info">
                        <input type="radio" name="book_id" value="{{ book.id }}" checked="checked">
                    </fieldset>
                    <button class="text-button text-small" type="submit" action="{% url 'borrow'%}">Borrow</button>
                </form>
            </td>
            {% elif book.get_status_display == "On Loan" %}
            <td></td>
            <td>
                <form method="POST" action="{% url 'borrow' %}">
                    {% csrf_token %}
                    <fieldset  class="hidden-info">
                        <input type="radio" name="book_id" value="{{ book.id }}" checked="checked">
                    </fieldset>
                    <button class="text-button text-small" type="submit" action="{% url 'borrow'%}">Return</button>
                </form>
            </td>
            {% elif book.get_status_display == "Unavailable" %}
                <td colspan="2"><p class="unavailable">This book cannot be borrowed.</p></td>
            {% else %}
                <td colspan="2"></td>
            {%endif%}
    {% endif %}
</tr>

main/templates/new_book.html
{% extends "base.html" %}
{% load static %}

{% block title %}Add a new Book{% endblock %}

{% block container %}list{% endblock %}

{% block content %}
<div class="main">
    <div class="text-container">
        {% if book %}
            <h1>Edit your book</h1>
        {% else %}
            <h1>Add a New Book</h1>
        {% endif %}

        <form method="POST" id="newBookForm" data-genre-url="{% url 'ajax_load_genres' %}">
            {% csrf_token %}
            {% for field in bookform %}
                <div class="field-container">
                    {{ field.errors }}
                    {{ field.label_tag }} <br> 

                    {% if book and field.name == "booktype" %}
                        {{ book.booktype }}
                    {% elif book and field.name == "genre" %}
                        {{ book.genre.genre }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                </div>
            {% endfor %}
            <button onclick="javascript:history.back();" class="text-button cancel-button">Cancel</button>
            <button type="submit" class="text-button submit-button">Submit</button>
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="{% static 'js/form.js' %}"></script>
{% endblock %}